### ISSUE TITLE
[BUG] Cannot log in with admin/admin

### ISSUE THREAD

**Issue by eostis** [opensearch-project/OpenSearch-Dashboards#1020]
I installed dashboards from docker compose (latest version). But cannot log in with admin/admin.

![image](https://user-images.githubusercontent.com/1785759/145723796-054c926c-2f7c-4240-9981-4b0809cfa582.png)

```
 opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5621"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]' # must be a string with no spaces when specified as an environment variable
      discovery.type: single-node
    volumes:
      - ./docker_volumes/opensearch-dashboards/data/:/usr/share/opensearch-dashboards/data
```

**Comment by kavilla** [comment]
Hello @eostis,

Thanks for opening this. The functionality is from the security plugin, but before re-routing this issue.

Can you share with me your full docker-compose file? I see volumes which you don't really have to do for `opensearch-dashboards` but I'm curious how your `opensearch-node1` looks like.

Does it look similar to the docker compose file provided in on this page: https://opensearch.org/docs/latest/opensearch/install/docker/?

**Comment by eostis** [comment]
Hello @kavilla,

Here is my docker file:
```
version: '3'

services:
  opensearch-node1:
    container_name: dev_opensearch # hostname in WPSOLR config
    build: .
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_master_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - default
      - wpsolr-external-network-created-with-docker-network-create
    volumes:
      - ./docker_volumes/opensearch/data/:/usr/share/opensearch/data
      #- ./my_opensearch.yml:/usr/share/opensearch/config/opensearch.yml

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]' # must be a string with no spaces when specified as an environment variable
      discovery.type: single-node
    volumes:
      - ./docker_volumes/opensearch-dashboards/data/:/usr/share/opensearch-dashboards/data

networks:
  wpsolr-external-network-created-with-docker-network-create:
    external: true

```
