### ISSUE TITLE
OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection

### ISSUE THREAD

**Issue by ichasco-heytrade** [opensearch-project/OpenSearch-Dashboards#1097]
I am getting errors when triying to connect to opensearch from opensearch-dashboard:

```
curl -XGET --insecure https://opensearch-cluster-master:9200 -u admin:admin -v
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 172.20.249.189:9200...
* Connected to opensearch-cluster-master (172.20.249.189) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*  CAfile: /etc/pki/tls/certs/ca-bundle.crt
*  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to opensearch-cluster-master:9200 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to opensearch-cluster-master:9200 
```

If I connect from my local host:

```
curl -v -XGET --insecure https://localhost:9200 -u admin:admin
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:9200...
* Connected to localhost (127.0.0.1) port 9200 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: DC=de; L=test; O=node; OU=node; CN=node-0.example.com
*  start date: Apr 22 03:43:47 2018 GMT
*  expire date: Apr 19 03:43:47 2028 GMT
*  issuer: DC=com; DC=example; O=Example Com Inc.; OU=Example Com Inc. Root CA; CN=Example Com Inc. Root CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Server auth using Basic with user 'admin'
> GET / HTTP/1.1
> Host: localhost:9200
> Authorization: Basic YWRtaW46dGFlYmFEARhZU5nZWVjX2FoMXNlLnJhZWM=
> User-Agent: curl/7.80.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 565
< 
{
  "name" : "opensearch-0",
  "cluster_name" : "production",
  "cluster_uuid" : "mG4RygycSv-x_Iv8Uz9bAA",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.2.3",
    "build_type" : "tar",
    "build_hash" : "8a529d77c7432bc45b005ac1c4ba3b2741b57d4a",
    "build_date" : "2021-12-21T01:36:21.407473Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
* Connection #0 to host localhost left intact
```

Versions:
Opensearch : 1.2.3
Opensearch-Dashboard: 1.2.0

Opensearch-Dashboard config:
```
opensearch_dashboards.yml:
      timelion.ui.enabled: true
      opensearch.username: admin
      opensearch.password: admin
      opensearch.ssl.verificationMode: "none"
      server.name: dashboards
      server.host: "0"
      server.ssl.enabled: "false"
      server.xsrf.whitelist:  [/_plugins/_security/saml/acs,/_opendistro/_security/saml/acs,/_plugins/_security/saml/acs/idpinitiated,/_opendistro/_security/saml/acs/idpinitiated,/_plugins/_security/saml/logout,/_opendistro/_security/saml/logout]
      opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
      opensearch_security.multitenancy.enabled: true
      opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
      opensearch_security.readonly_mode.roles: ["kibana_read_only"]
```

**Comment by kavilla** [comment]
Hello @ichasco-heytrade, thanks for opening this! OpenSSL would be a concept of the security plugin. But before re-routing this issue. How are you running OpenSearch and OpenSearch Dashboards? Are you running it from the docker images, executable, or from source?

**Comment by ichasco-heytrade** [comment]
Hi @kavilla, I have deployed opensearch and opensearch-dashboard with HELM in Kubernetes.

Thanks!

**Comment by kavilla** [comment]
> Hi @kavilla, I have deployed opensearch and opensearch-dashboard with HELM in Kubernetes.
> 
> Thanks!

Apologies about the delay. Was going to comment potentially related to the `server.host: "0"`. If you don't mind sharing, what was missing? Could have been mitigated with proper documentation?

**Comment by ichasco-heytrade** [comment]
Hi @kavilla sorry, maybe I have not explained myself well. I have deployed it with HELM but it doesn't work. Because the dashboard can't connect with opensearch. I have deployed with the demo configuration. I don't know what is missing or what is wrong.

If you need the configuration of opensearch:

opensearch.yml
```
opensearch.yml: |
      cluster.name: production
      network.host: 0.0.0.0
      node.max_local_storage_nodes: 3
      plugins:
        security:
          disabled: false
          ssl:
            transport:
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
              enforce_hostname_verification: false
            http:
              enabled: true
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
          allow_unsafe_democertificates: true
          allow_default_init_securityindex: true
          authcz:
            admin_dn:
              - CN=kirk,OU=client,O=client,L=test,C=de
          audit.type: internal_opensearch
          enable_snapshot_restore_privilege: true
          check_snapshot_restore_write_privileges: true
          restapi:
            roles_enabled: ["all_access", "security_rest_api_access"]
          system_indices:
            enabled: true
            indices:
              [
                ".opendistro-alerting-config",
                ".opendistro-alerting-alert*",
                ".opendistro-anomaly-results*",
                ".opendistro-anomaly-detector*",
                ".opendistro-anomaly-checkpoints",
                ".opendistro-anomaly-detection-state",
                ".opendistro-reports-*",
                ".opendistro-notifications-*",
                ".opendistro-notebooks",
                ".opendistro-asynchronous-search-response*",
              ]
```

config.yml
```
         _meta:
            type: "config"
            config_version: 2

          config:
            dynamic:
              http:
                anonymous_auth_enabled: false
              authc:
                basic_internal_auth_domain:
                  description: "Authenticate via HTTP Basic against internal users database"
                  http_enabled: true
                  transport_enabled: true
                  order: 0
                  http_authenticator:
                    type: basic
                    challenge: true
                  authentication_backend:
                    type: intern
```

Thanks!
