### ISSUE TITLE
[BUG] login failed: Invalid username or password, please try again

### ISSUE THREAD

**Issue by r0736202** [opensearch-project/OpenSearch-Dashboards#1611]
I need to login to access my opensearch dashboard
but it says Invalid username or password, please try again
![image](https://user-images.githubusercontent.com/43341291/169775566-bb27d9be-2a10-468a-9713-cef7218713c1.png)

Ive never changed the credentials, so i used admin:admin --> DOESNT WORK
i looked into my opensearch_dashboard.yml CONFIG file and it says 
![image](https://user-images.githubusercontent.com/43341291/169774999-e5b86878-8b15-4cfd-8f5b-5ac57118b5e7.png)
kibanaserver:kibanaserver
but that also didnt work

im clueless, please help!

im using the latest opensearch-oss image and opensearch-dashboard via docker-compose
![image](https://user-images.githubusercontent.com/43341291/169775449-ceb0a2a9-7887-4777-a625-5668df6fe276.png)
this is my docker-compose for opensearchdashboard

**Comment by kavilla** [comment]
Hello @r0736202,

Thank you for opening. Are you loading your `opensearch_dashboards.yml` like [this](https://github.com/opensearch-project/OpenSearch/pull/3346)? If so you probably don't need to set the environment variable. Can you  inspect the network tab and tell me what you see?

Or if you are able to share your `docker-compose` file. I believe seeing `OPENSEARCH_HOSTS=["http:` looks incorrect and most likely your OpenSearch Dashboards is starting but not actually communicating with OpenSearch.

**Comment by ananzh** [comment]
Hi @r0736202 

could try change http to https and see if work

**Comment by r0736202** [comment]
> Hello @r0736202,
> 
> Thank you for opening. Are you loading your `opensearch_dashboards.yml` like [this](https://github.com/opensearch-project/OpenSearch/pull/3346)? If so you probably don't need to set the environment variable. Can you inspect the network tab and tell me what you see?
> 
> Or if you are able to share your `docker-compose` file. I believe seeing `OPENSEARCH_HOSTS=["http:` looks incorrect and most likely your OpenSearch Dashboards is starting but not actually communicating with OpenSearch.

No im not loading my .yml like that, and this is my network 
![image](https://user-images.githubusercontent.com/43341291/169976303-0d419f74-56cd-4a11-b985-f54d836ce002.png)
`version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
#      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50%$
      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security$
#      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - opensearch-conf1:/usr/share/opensearch/config:Z
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-node2:
    image:  opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
#      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "DISABLE_SECURITY_PLUGIN=true" # disables security plugin entirely in OpenSearch by setting plugins.security$
#      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - opensearch-conf2:/usr/share/opensearch/config:Z
    networks:
      - opensearch-net
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.13.4
    container_name: logstash
    ports:
      - 0.0.0.0:5044:5044
      - 0.0.0.0:5045:5045
    volumes:
      - logstash-pipeline:/usr/share/logstash/pipeline:Z
#      - logstash-conf:/usr/share/logstash/config:Z

    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200","http://opensearch-node2:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
#      - opensearch.username="admin"
  #    - opensearch.password="admin"
    volumes:
      - opendashboard:/usr/share/opensearch-dashboards/config:Z

    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:
  opensearch-conf1:
  opensearch-conf2:
  logstash-pipeline:
  opendashboard:
networks:
  opensearch-net:
`
this is my docker compose.

**Comment by ananzh** [comment]
@r0736202 
I do see some strange stuff in this docker-compose file. Since you are trying to disable security in os and osd. then the admin and admin should should not work. If you want to security, you could modify your docker-compose file by removing the `DISABLE_SECURITY_PLUGIN=true` , `DISABLE_SECURITY_DASHBOARDS_PLUGIN=true` and etc. A reference is below:

```
version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.0.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-node2:
    image: opensearchproject/opensearch:2.0.0
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.0.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]' # must be a string with no spaces when specified as an environment variable
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
```

**Comment by ananzh** [comment]
@r0736202 I did check the below docker with security and `admin:admin` works fine. More reference could be found [here](https://opensearch.org/docs/latest/opensearch/install/docker/)

**Comment by r0736202** [comment]
> @r0736202 I did check the below docker with security and `admin:admin` works fine. More reference could be found [here](https://opensearch.org/docs/latest/opensearch/install/docker/)

yeah when i tested it, i ofcourse enabled security and it still wouldnt work
now ive found my problem:
i dont have the security plugin installed for opensearch (not opensearch dashboard)
plugin: opensearch-security    1.3.2.0

but it doesnt let me install it

**Comment by ananzh** [comment]
@r0736202 did you remove `DISABLE_SECURITY_PLUGIN=true`? or could you try my docker-compose.yml and see if it could help you start the container and run OSD successfully ?

**Comment by eogredici** [comment]
Hi @r0736202 , 
If your problem still persists, I faced the same problem. I fixed this issue, change plugins.security.disabled to:false
at opensearch.yml. Your specs may be plugins.security.disabled to:true.


Opensearch version: 2.3.0
OSD version: 2.3.0
I used tarball for the install method.

**Comment by ashokfredrick** [comment]
Hi Friends, I'm also facing the same issue, please advise.

Issue : Not able to login with initial ID&pwd in opensearch dashbaords and getting 404.

RPM installation

**Comment by ashokfredrick** [comment]
Hi @eogredici,

Tried with opensearch.yml / plugins.security.disabled to:false but not working for me.Any idea, please?

**Comment by kavilla** [comment]
> Hi @eogredici,
> 
> Tried with opensearch.yml / plugins.security.disabled to:false but not working for me.Any idea, please? 

Hello!

Can you confirm if the security dashboards plugin is still enabled or installed?

You will have to make sure to disable it for dashboards and remove any configurations related to it in `opensearch_dashboards.yml`


REF: https://opensearch.org/docs/latest/security-plugin/configuration/disable

**Comment by ashokfredrick** [comment]
Hi Kavilla,

Thanks for your reply.

Can you confirm if the security dashboards plugin is still enabled or installed?
You will have to make sure to disable it for dashboards and remove any configurations related to it in opensearch_dashboards.yml
<ashok> Means you want to uninstall all plugins (currently 10(2.3) plugins are there in my server? 
have added plugins.security.disabled: true in opensearch.yml , possible pls share me the opensearch and opensearch-dashboard.yml for rpm installation for the default user (kibanaserver).

Thanks in advance.

**Comment by eogredici** [comment]
> Hi @eogredici,
> 
> Tried with opensearch.yml / plugins.security.disabled to:false but not working for me.Any idea, please?

Hi @ashokfredrick ,

Could you please share your **opensearch.yml**

I will share  my opensearch.yml and opensearch_dashboards.yml to bellow;

**opensearch.yml**

`network.host: 0.0.0.0
discovery.type: single-node
plugins.security.disabled: false


plugins.security.ssl.transport.pemcert_filepath: $YOUR_PATH/node1.pem
plugins.security.ssl.transport.pemkey_filepath: $YOUR_PATH/node1-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: $YOUR_PATH/root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: $YOUR_PATH/node1.pem
plugins.security.ssl.http.pemkey_filepath: $YOUR_PATH/node1-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: $YOUR_PATH/root-ca.pem
plugins.security.allow_default_init_securityindex: true
plugins.security.authcz.admin_dn:
#Change it according to your configuration
  - 'CN=XXXX,OU=XXXX,O=XXXX,L=XXXX,ST=XXXX,C=XXXX'
plugins.security.nodes_dn:
#Change it according to your configuration
  - 'CN=XXXX,OU=XXXX,O=XXXX,L=XXXX,ST=XXXX,C=XXXX'
plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
`



**opensearch_dashboards.yml** ;

`opensearch.hosts: ["https://localhost:9200"]
opensearch.ssl.verificationMode: none
opensearch.username: "**username**"
opensearch.password: "**password**"
opensearch.requestHeadersAllowlist: [ authorization,securitytenant ]
server.ssl.enabled: false
#server.ssl.certificate: $YOUR_PATH/client.pem
#server.ssl.key: $YOUR_PATH/client-key.pem
#opensearch.ssl.certificateAuthorities: [ "**$YOUR_PATH**/root-ca.pem","**$YOUR_PATH**/root-ca-key.pem"]
opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
opensearch_security.cookie.secure: false
`

**Comment by ashokfredrick** [comment]
Hi @eogredici,

Thanks for the details.

I have tried with your yml (opensearch.yml and opensearch-dashboard.yml) file without plugins.security settings for opensearch.yml and it's not working for me.
Error message : Error Code:404 / Unauthorized / authentication required.
FYI, i'm not using any ssl/certs/ldaps config from my server and just trying with default.

Please advise.

**Comment by jamie-chapman** [comment]
Having the same issue here

**Comment by quickbooks2018** [comment]
I am using terraform getting the same error "Log In Invalid username or password, please try again"

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::123456789:user/cloud_user",
          "*"
        ]
      },
      "Action": "*:*",
      "Resource": "arn:aws:es:us-east-1:123456789:domain/cloudgeeks-opensearch/*"
    }
  ]
}



module.opensearch.elasticsearch_opensearch_roles_mapping.master_user_arn["security_manager"]: Creating...
module.opensearch.elasticsearch_opensearch_roles_mapping.master_user_arn["all_access"]: Creating...
╷
│ Error: ElasticSearch version 2.3.0 is older than 6.0.0 and is not supported, flavor: 0.
│
│   with module.opensearch.elasticsearch_opensearch_roles_mapping.master_user_arn["all_access"],
│   on .terraform/modules/opensearch/role_mapping.tf line 16, in resource "elasticsearch_opensearch_roles_mapping" "master_user_arn":
│   16: resource "elasticsearch_opensearch_roles_mapping" "master_user_arn" {
│
╵
╷
│ Error: ElasticSearch version 2.3.0 is older than 6.0.0 and is not supported, flavor: 0.
│
│   with module.opensearch.elasticsearch_opensearch_roles_mapping.master_user_arn["security_manager"],
│   on .terraform/modules/opensearch/role_mapping.tf line 16, in resource "elasticsearch_opensearch_roles_mapping" "master_user_arn":
│   16: resource "elasticsearch_opensearch_roles_mapping" "master_user_arn" {
│

**Comment by ananzh** [comment]
@quickbooks2018 
Seems there are two issues here:
* Invalid Username or Password: This error is occurring because the username or password you are using to authenticate with AWS is incorrect.
* Version conflict `Error: ElasticSearch version 2.3.0 is older than 6.0.0 and is not supported, flavor: 0.`. Seems you are using ElasticSearch 2.3.0 or OpenSearch? But ur terraform script suggests that you must use a version of Elasticsearch that is 6.0.0 or newer.

**Comment by feiyu15** [comment]
> > Hi @eogredici,
> > Tried with opensearch.yml / plugins.security.disabled to:false but not working for me.Any idea, please?
> 
> Hello!
> 
> Can you confirm if the security dashboards plugin is still enabled or installed?
> 
> You will have to make sure to disable it for dashboards and remove any configurations related to it in `opensearch_dashboards.yml`
> 
> REF: https://opensearch.org/docs/latest/security-plugin/configuration/disable

thank you.

I had the same problem and it was resolved.
If the security configuration is not enabled.
Then both opensearch and opensearch dashboard need to turn off security.
opensearch:
plugins.security.disabled: true
opensearch dashboard:
Delete the security plugins folder
 
https://opensearch.org/docs/latest/security/configuration/disable/
https://opensearch.org/docs/latest/install-and-configure/install-dashboards/plugins/#remove-plugins

**Comment by kid1412621** [comment]
is there any env var like to config in docker-compose.yml?
OPENSEARCH_USERNAME=admin
OPENSEARCH_PASSWORD=admin

**Comment by salamer** [comment]
Any Progress?

**Comment by Uysim** [comment]
Any update about this? I should be the priority one.

**Comment by ananzh** [comment]
@Uysim @salamer 
I think from the previous discussion there are several working options
* https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1611#issuecomment-1142733223 which has a reference docker-compose file.
* https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1611#issuecomment-1637553124 

What are your docker-compose file and errors?

**Comment by aleksbal** [comment]
I also experience the same problem. Just can't log in with default credentials set in opensearch-dashboards. No Docker, direct installation. In my opinion cluster nodes and their security config has nothing to do with the dashboards which is an application on its own. Having said that, it is very, very annoying and I thing I 'll throw it away it is just not worthy my time and effort to deal with such trivial bugs...

**Comment by ajbeach2** [comment]
I am having the same issue. I am using the docker-compose file provided in the docks, and the dashboard does not allow me to login with admin/password that is set the docker-compose file

**Comment by t-morisawa** [comment]
I cannot login admin:admin either.
But I was able to login kibanaserver:kibanaserver.

**Comment by Bdthomson** [comment]
I can confirm that kibanaserver:kibanaserver on the Opensearch dashboard works. I was following https://opensearch.org/docs/latest/getting-started/quickstart/ and no variation of admin username and  `admin` as the password, or trying my custom admin password would work.

**Comment by isliudong** [comment]
有人吗，admin 设置密码后无法登录 无语了

**Comment by dipanshuchaubey** [comment]
username: `kibanaserver`
password: `kibanaserver`

worked for me, there is no `admin` user

**Comment by bonanzadigger** [comment]
For me also nothing is working as password combination. "kibanaserver" is NOT WORKING!!
I have installed without Docker as normal installation on Ubuntu 22.04 (installed version of os and osd: v2.5.0)

**Comment by ValfarDeveloper** [comment]
Things like this makes me wondering if I'm in the right place, or if I should migrate back to Elastic Search. This is very simple, and hasn't been resolved yet, I don't want to imagine what is happening with bigger/critical issues.

**Comment by omar-sif** [comment]
If you're trying to disable security, copy the .yml from here : [https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#sample-docker-compose-file-for-development](url) or at least try to do it the same they did it there. 
I had the same problem with opensearch dashboards not logging after I disabled security, i just copied this config from the official docs and it worked right away,
 All other solutions either don't work or require a lot of configuration which gets very confusing sometimes.

**Comment by gtsopour** [comment]
Same issue here. I have provisioned an OpenSearch Cluster in AWS with crossplane (apiVersion: opensearch.aws.upbound.io/v1beta1, kind: Domain)and somehow the initial credentials are not valid anymore suddenly.

**Comment by jaydorsey** [comment]
I also couldn't get the credentials examples to work following some of the suggestions in this thread and a number of others (admin, kibanaserver, setting the initial, etc.)

I was finally able to get a working example (I think? the dashboard loads at least) with this [docker-compose.yml](https://gist.github.com/jaydorsey/5aea3a3e5a9fc41d3d493b16a3c754ed) example based on one of the examples above; security is disabled and there is no login, you just visit localhost:5601 and you're on the dashboard

In my case, this is 100% for local development/exploration only so that's fine.

**Comment by peter-hanzo** [comment]
I solved the problem "Invalid username or password" opensearch-dashboards

maybe it will be useful:

my settings with which I entered without a password

```
opensearch:
    environment:
      - discovery.type=single-node  
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Piteee222-222
      - OPENSEARCH_INITIAL_ADMIN_USER=admin
      - plugins.security.disabled=true
      - OPENSEARCH_SECURITY_DISABLED=true
      - plugins.security.ssl.http.enabled=false
      - plugins.security.audit.config.enable_transport=true
      - plugins.security.allow_unsafe_democertificates=true
      - plugins.security.allow_default_init_securityindex=true

opensearch-dashboards:
environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
```

**Comment by pavl0v** [comment]
Hello. Here is my `docker-compose.yml` to setup OpenSearch single-node cluster and Dashboard secured with password (login: `admin`, password: `StrongPassword123!!`):
```yaml
services:

  opensearch:
    image: opensearchproject/opensearch:3
    container_name: opensearch
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - type: volume
        source: opensearch_vol
        target: /usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: true
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: StrongPassword123!!

  opensearch_ui:
    image: opensearchproject/opensearch-dashboards:3
    container_name: opensearch_ui
    depends_on:
      opensearch:
        condition: service_started
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'

volumes:
  opensearch_vol:
    driver: local
```
