### ISSUE TITLE
[BUG] Unable to change default admin credentials. "Resource 'admin' is read-only."

### ISSUE THREAD

**Issue by Just5KY** [opensearch-project/OpenSearch-Dashboards#1694]
**Describe the bug**
- Unable to change default admin credentials

- OpenSearch Dashboard default admin credentials is admin:admin, i want to disable the user or change that credentials for it.
- Tried to change credentials from Dashboard but im greeted with `Failed to reset password. {"status":"FORBIDDEN","message":"Resource 'admin' is read-only."}`
- Same error if i try to change from `http://opensearch-dashboard:5601/app/security-dashboards-plugin#/users/edit/admin`

**To Reproduce**

1. Go to 'Opensearch-Dashboard's /app/security-dashboards-plugin#/users & Edit internal user'
2. Select `admin` user 
3. Make changes and hit Save changes
4. Gets `Failed to reset password. {"status":"FORBIDDEN","message":"Resource 'admin' is read-only."}`

**Expected behavior**
- Admin user credentials should be changed

**OpenSearch Version**
- 2.0

**Dashboards Version**
- 2.0

_Also tried with version 1.3.x for both, same error_

**Plugins**

```bash
[opensearch@085047a98b3d bin]$ opensearch-plugin list
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ml
opensearch-notifications
opensearch-notifications-core
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-sql
```

```bash
[opensearch-dashboards@a354e8661a71 ~]$ bin/opensearch-dashboards-plugin list
alertingDashboards@2.0.0.0
anomalyDetectionDashboards@2.0.0.0
ganttChartDashboards@2.0.0.0
indexManagementDashboards@2.0.0.0
notificationsDashboards@2.0.0.0
observabilityDashboards@2.0.0.0
queryWorkbenchDashboards@2.0.0.0
reportsDashboards@2.0.0.0
securityDashboards@2.0.0.0
```

**Screenshots**
![image](https://user-images.githubusercontent.com/71321862/172604681-16fb79fb-c5e4-43e6-a0e6-8a00491ed7c7.png)

**Host/Environment (please complete the following information):**
 - OS: Windows 10
 - Firefox 101.0

**Additional context**
- Docker-compose
```yml
version: '3'

volumes:
  opensearch-data:

services:
  opensearch:
    image: opensearchproject/opensearch
    container_name: opensearch
    restart: unless-stopped
    environment:
      - cluster.name=opensearch
      - node.name=opensearch
      #      - discovery.seed_hosts=opensearch
      #      - cluster.initial_master_nodes=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true 
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" 
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards
    container_name: opensearch-dashboards
    restart: unless-stopped
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
```
