### ISSUE TITLE
[BUG] label template not showing value for url-image

### ISSUE THREAD

**Issue by Julien-athstat** [opensearch-project/OpenSearch-Dashboards#1888]
**Describe the bug**
Label Template not showing {{Value}} when changing field format to url-image 

**To Reproduce**
1. Go to '[Stack Management]
[Index patterns]'
2. Click on 'Edit' to edit a string field
3. Set "URL template" and "Label template"
4. Sample will show expected behavior
5. Go to Discover or a sample table with that field; ONLY the image will show NOT the Label

**Expected behavior**
That edited field should show the url-image and the field {{value}} as label next to the image

**OpenSearch Version**
1.2.0
**Dashboards Version**
1.2.0

**Screenshots**
![Screenshot 2022-07-12 at 19 03 06](https://user-images.githubusercontent.com/85301727/178551168-794e7da3-730a-456e-88cb-9a8eb98a4075.png)
![Screenshot 2022-07-12 at 19 03 26](https://user-images.githubusercontent.com/85301727/178551199-f98970c0-fce5-452d-8a8b-56cff83cb134.png)

**Host/Environment (please complete the following information):**
 - OS: macOS Monterey
 - Browser and version: Chrome Version 103.0.5060.114 (Official Build) (x86_64)

**Comment by ananzh** [comment]
I can re-produce this issue. 
<img width="487" alt="Screen Shot 2022-07-15 at 12 09 25" src="https://user-images.githubusercontent.com/79961084/179302598-0f225f9b-90c4-4ac2-b329-1da893967b5c.png">



The reason  is that the icons loaded are missing basePath, so the path is not correct and img can't be found. By adding the basePath in the browser, the problem is solved.
<img width="420" alt="Screen Shot 2022-07-15 at 13 01 36" src="https://user-images.githubusercontent.com/79961084/179302772-3b2222e1-9a0a-4e30-9989-b6ca83e8c2f8.png">

<img width="347" alt="Screen Shot 2022-07-15 at 12 37 44" src="https://user-images.githubusercontent.com/79961084/179302789-df0f8f20-d200-4463-9e4e-4e43e3b70a52.png">


Issue code is at [UrlFormatEditor](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/e3b34df1dea59a253884f6da4e49c3e717d362c9/src/plugins/index_pattern_management/public/components/field_editor/components/field_format_editor/editors/url/url.tsx#L88) component.

I will keep research on how to add basePath to this component.

**Comment by ananzh** [comment]
This is because in url format htmlConverter (https://github.com/opensearch-project/OpenSearch-Dashboards/blob/7f7c7449e8fcf3a3ad58bd8f009cc7830131758b/src/plugins/data/common/field_formats/converters/url.ts#L158)](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/808129bcf077912c2ed4af5aea517c32ec1315a5/src/plugins/data/common/field_formats/converters/url.ts#L160)

```
const baseUrl = escape(this.formatUrl(rawValue));
```
the baseUrl doesn't have the basePath (the random 3 letters, like rtl). I think there are two ways to fix this. 

### Add the basePath in url.ts

```
const baseUrl = escape(this.formatUrl(rawValue));
const url = basePath ? basePath.concat(baseUrl) : baseUrl;
```

### change urlTemplate
We could also modify this from `formatUrl(rawValue)` method 
```
private formatUrl(value: string): string {
    const template = this.param('urlTemplate');
    if (!template) return value;

    return this.compileTemplate(template)({
      value: encodeURIComponent(value),
      rawValue: value,
    });
}
```
we could see it is compile the `urlTemplate`. urlTemplate for img is created [here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d7004dc5b0392477fdd54ac66b29d231975a173b/src/plugins/index_pattern_management/public/components/field_editor/components/field_format_editor/editors/url/url.tsx#L118). The default value is null. Once the url format img type is chosen, it will be set in indexPattern. An index pattern is constructed like 

```
- id: "90943e30-9a47-11e8-b64d-95841ca0b247"
- title: "opensearch_dashboards_sample_data_logs"
- Fields (FldList(41)) // contains all field definitions
For example, for clientip, an IndexPatternField object will be
displayName: clientip
spec:
   aggregatable: true
   name: "clientip"
   type: "ip"
   format: DecoratedFieldFormat
       _params
           parsedUrl
               	basePath: "/jxv"                  
                origin: "http://localhost:5603"                  
                pathname: "/jxv/app/home"
           **urlTemplate: undefined // it will be reset**
           type: "img"

- fieldFormats (FieldFormatsRegistry object which register about 15 format types)
```
Currently it is set to a fixed value 
```
/plugins/indexPatternManagement/assets/icons/{{value}}.png
```

To fix, we could change it to a func to fetch basePath and prepend it to the original path
```
private getIconPath = () => {
    const iconPath = `/plugins/indexPatternManagement/assets/icons/{{value}}.png`;
    return this.context?.services.http
      ? this.context.services.http.basePath.prepend(iconPath)
      : iconPath;
};
```
