### ISSUE TITLE
Docker dev environment support 

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#2196]
**Is your feature request related to a problem? Please describe.**

Currently, development for OSD is optimized for the Linux environment. This adds friction to the development flow even if tools like remote dev servers are used. E.g. functional testing.

**Describe the solution you'd like**

Add a docker dev container so that every contributor can work on an identical dev environment and not worry about local OS limitations. This can additionally simplify the process of development with a bundled version of OpenSeach and plugins by simply switching out the dev container used.

**Describe alternatives you've considered**

Rolling out supported distributions for every major platform available.

**Additional context**

**Comment by joshuarrrr** [comment]
@ashwin-pc +1 this sounds great. Can you provide a few more concrete details about what you envision the docker startup and dev process to look like (rough pseudo-flow comparison to the current local dev would be fine).

**Comment by ashwin-pc** [comment]
Havent had the time to setup a POC for this yet but it should be fairly simple. We can have a base docker image that has all the dependencies we need to build OpenSearch Dashboards and build it and then use a compose file like this:

```yaml
verison: "3.9"
services:
  os:
    image: opensearchproject/opensearch:latest
    ports:
      - "9300:9300"
    # Other env params
  osd:
    build: . # Or alternatively it can be an base image with all the dependencies installed that we can provide
    ports:
      - "5601:5601"
    volumes:
      - "./:{container_path_to_project_root}/"
 ```

to setup any docker image for OpenSearch Engine. Now we can connect to the osd container to run any commands that would not be supported on the native OS and any changes made to the code during development would run in the docker environment
