### ISSUE TITLE
[BUG] Dashboard fails to connect when using securityconfig

### ISSUE THREAD

**Issue by jonathon2nd** [opensearch-project/OpenSearch-Dashboards#2712]
**Describe the bug**

Dashboard does not connect when trying to set and use different passwords.

**To Reproduce**
Deploy cluster from operator.

`securityconfig-secret` is taken from https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/examples/opensearch-cluster-securityconfig.yaml
I have rehashed passwords by using the `hash.sh` I found on the opensearch pod, as getting it working locally failed.

`admin-credentials-secret`
```
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-credentials-secret
  namespace: labs-opensearch
type: Opaque
stringData:
  username: admin
  password: PASSWORD
```

Values for cluster
```
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: labs-cluster
  namespace: labs-opensearch
spec:
  security:
    tls:  # Everything related to TLS configuration
      transport:  # Configuration of the transport endpoint
        generate: true  # Have the operator generate and sign certificates
        perNode: true  # Separate certificate per node
      http:  # Configuration of the HTTP endpoint
        generate: true  # Have the Operator generate and sign certificates
    config:
      securityConfigSecret:
        name: securityconfig-secret
      adminCredentialsSecret:
        name: admin-credentials-secret
  general:
    serviceName: labs-cluster
    version: 1.3.1
    setVMMaxMapCount: true
  dashboards:
    enable: true
    additionalConfig:
      opensearch_security.auth.type: "proxy"
      opensearch.requestHeadersWhitelist: |
        ["securitytenant","Authorization","x-forwarded-for","x-auth-request-access-token", "x-auth-request-email", "x-auth-request-groups"]
      opensearch_security.multitenancy.enabled: "true"
      opensearch.username: "admin"
      opensearch.password: "PASSWORD"
    tls:
      enable: true  # Configure TLS
      generate: true  # Have the Operator generate and sign a certificate
    version: 1.3.1
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "50Gi"
      jvm: -Xmx1024M -Xms1024M #Set to half of memory request
      persistence:
        pvc:
          storageClass: linstor-replica-one-local
          accessModes:
          - ReadWriteOnce
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"
        - "master"
````

**Expected behavior**
Expect dashboard to connect, like when testing without changing passwords

**OpenSearch Version**
Please list the version of OpenSearch being used.
Operator: 2.1.1
general.version: 1.3.1

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.
dashboards.version: 1.3.1

**Plugins**

Please list all plugins currently enabled.
Default

**Screenshots**

![image](https://user-images.githubusercontent.com/52681917/199281248-db5f560c-ddbe-433c-bd74-2c5a48f7ee4f.png)

**Host/Environment (please complete the following information):**
 - OS: k8s
 - Browser and version: chrome Version 107.0.5304.87 (Official Build) (64-bit)

**Additional context**

Following quite the rabbit hole trying to get this working. I have been following https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md as well as I can, 404'd links aside. 

I have consulted https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/config/opensearch_dashboards.yml and have tried a number of different `dashboards.additionalConfig` settings, including empty, and I get the same results. I have defaulted to trying with the admin user, as you can see in provided yaml.

Looked at https://github.com/opensearch-project/security/issues/1787, https://github.com/opensearch-project/security/pull/1836, https://github.com/opensearch-project/security/issues/1576, https://github.com/Opster/opensearch-k8s-operator/issues/305 hoping to find some clues, so far no.
