### ISSUE TITLE
[Index Management][BUG] URL img field format doesn't properly show sample images

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#2928]
**Describe the bug**

When click `index pattern` in `Stack Mangement` then use `URL` as the field format and set `img` as type, field formator doesn't properly show sample images.

<img width="980" alt="Screen Shot 2022-11-25 at 14 41 37" src="https://user-images.githubusercontent.com/79961084/204061053-5730e60e-bcb3-478a-b3d8-38c67a8975f5.png">

**To Reproduce**
1. Click `index pattern` in `Stack Mangement`
2. Choose `opensearch_dashboards_sample_data_logs`
3. Search field `clientip` and click the edit button on the right
4. Set `URL` as the field format and set `Image` as type
<img width="972" alt="Screen Shot 2022-11-25 at 14 41 25" src="https://user-images.githubusercontent.com/79961084/204061044-9448f6d3-0cac-4a2a-b0d4-f7cc00d54de3.png">

**Expected behavior**

Image displays correctly.

<img width="368" alt="Screen Shot 2022-11-25 at 14 47 40" src="https://user-images.githubusercontent.com/79961084/204061278-5bec2aae-b77c-4954-9d62-7160b0e7b5b3.png">

**Comment by ananzh** [comment]
This is because in url format htmlConverter (https://github.com/opensearch-project/OpenSearch-Dashboards/blob/7f7c7449e8fcf3a3ad58bd8f009cc7830131758b/src/plugins/data/common/field_formats/converters/url.ts#L158)](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/808129bcf077912c2ed4af5aea517c32ec1315a5/src/plugins/data/common/field_formats/converters/url.ts#L160)

```
const baseUrl = escape(this.formatUrl(rawValue));
```
the baseUrl doesn't have the basePath (the random 3 letters, like rtl). I think there are two ways to fix this. 

### Add the basePath in url.ts

```
const baseUrl = escape(this.formatUrl(rawValue));
const url = basePath ? basePath.concat(baseUrl) : baseUrl;
```

### change urlTemplate
We could also modify this from `formatUrl(rawValue)` method 
```
private formatUrl(value: string): string {
    const template = this.param('urlTemplate');
    if (!template) return value;

    return this.compileTemplate(template)({
      value: encodeURIComponent(value),
      rawValue: value,
    });
}
```
we could see it is compile the `urlTemplate`. urlTemplate for img is created [here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d7004dc5b0392477fdd54ac66b29d231975a173b/src/plugins/index_pattern_management/public/components/field_editor/components/field_format_editor/editors/url/url.tsx#L118). The default value is null. Once the url format img type is chosen, it will be set in indexPattern. An index pattern is constructed like 

```
- id: "90943e30-9a47-11e8-b64d-95841ca0b247"
- title: "opensearch_dashboards_sample_data_logs"
- Fields (FldList(41)) // contains all field definitions
For example, for clientip, an IndexPatternField object will be
displayName: clientip
spec:
   aggregatable: true
   name: "clientip"
   type: "ip"
   format: DecoratedFieldFormat
       _params
           parsedUrl
               	basePath: "/jxv"                  
                origin: "http://localhost:5603"                  
                pathname: "/jxv/app/home"
           **urlTemplate: undefined // it will be reset**
           type: "img"

- fieldFormats (FieldFormatsRegistry object which register about 15 format types)
```
Currently it is set to a fixed value 
```
/plugins/indexPatternManagement/assets/icons/{{value}}.png
```

To fix, we could change it to a func to fetch basePath and prepend it to the original path
```
private getIconPath = () => {
    const iconPath = `/plugins/indexPatternManagement/assets/icons/{{value}}.png`;
    return this.context?.services.http
      ? this.context.services.http.basePath.prepend(iconPath)
      : iconPath;
};
```
