### ISSUE TITLE
Support restart upgrades to OpenSearch Dashboards 1.0 from Kibana v7.10.x

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch-Dashboards#334]
Upgrading your cluster from ElasticSearch to OpenSearch and OpenSearch Dashboards is just like upgrading your cluster between versions of ElasticSearch and Kibana. Specifically, OpenSearch supports rolling upgrades and restart upgrades from ElasticSearch 6.8.0 through ElasticSearch 7.10.2 and to OpenSearch 1.0. OpenSearch Dashboards supports restart upgrades from Kibana 6.8.0 through Kibana 7.10.2 and to OpenSearch Dashboards 1.0.

**Comment by dblock** [comment]
@seanneumann which versions do we want to be drop-in replacement for?

**Comment by dblock** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/325

**Comment by seanneumann** [comment]
Primary focus is to support Kibana 7.10.2 to OpenSearch Dashboard 1.0.0.

**Comment by kavilla** [comment]
* Index renamed from .kibana to .opensearch_dashboards
    * Will impact auto-migration because it will look for the default index which is now currently .opensearch_dashboards and will not see any index of that name so it will not migrate but just create the new index.


* Object keys that have be renamed that will impact the ability to automatically migrate saved objects for .kibana to .opensearch_dashboards because it has no value to map to:
    * kibanaSavedObjectMeta  → opensearchDashboardsSavedObjectMeta
    * esTypes → opensearchTypes
    * timelion.* → timeline.*
* Object values that will have to be renamed that will impact the ability to automatically migrate saved objects that might impact the functionality:
    * indexRefName:"opensearchDashboardsSavedObjectMeta.searchSourceJSON.index"}
    * URLs stored in the saved objects that depend on  URL that contains the route: kibana 
    * Indices for example if the expression had .es(*) we changed to .opensearch(*) this will break any saved visualizations since it will try to query for .es(*) which does not exist.
    * DQL (previously KQL) can have queries saved for example: _index: ".kibana" would need to be _index: ".opensearch_dashboards"
* In general, any URLs that contains the route kibana 
    * localhost:5603/qmg/app/management/kibana/* → localhost:5603/qmg/app/management/opensearch-dashboards/*
    * localhost:5603/qmg/app/kibana_overview#/ → localhost:5603/qmg/app/opensearch_dashboards_overview#/
* Map settings were changed, however this might not have any impact for people.
    * includeElasticMapsService → includeOpenSearchMapsService
    * proxyElasticMapsServiceInMaps → proxyOpenSearchMapsServiceInMaps

**Comment by kavilla** [comment]
There are a couple solutions that we are thinking about the most important tenant being "drop-in", the consideration on keeping `.kibana` index the same seems like the definite outcome as of right now. Just how we deal with the changed fields that we updated that will definitely require code change.

**Comment by kavilla** [comment]
Kibana did not support rolling upgrades, OpenSearch Dashboards will not for this release either.

**Comment by kavilla** [comment]
To summarize, keep settings breaking (kibana.yml --> opensearch_dashboards.yml). We could provide a tool for updating or provide documentation.

For breaking changes will restore the default index and restore data fields (not aliasing, aliasing has pitfalls). This shouldn't really trigger a migration and will hit the tenant of allowing customers to rollback from OpenSearch Dashboards to Kibana. However, this isn't really fully forward compatible with future expectations (whatever that will be perhaps 0 reference to kibana), so there will require more work on that end. But once we go from Kibana to OpenSearch Dashboards 1.0 then OpenSearch Dashboards 1.0 to vNext, we are not blocked by the tenant of allowing rolling back form OpenSearch Dashboards to Kibana. This was discussed to be the safest option and relatively reduce time to meet announced timelines. Another CON will be customers could use dev tools and see these values, but this is not a violation of license since it is functionality issue (or MAGIC WORDS). If it is a magic word then it is allowed even if it might show up on the screen.

However, we need to see if we can replace URL with 302 or restore back to kibana for example: localhost:5603/qmg/app/management/kibana/* → localhost:5603/qmg/app/management/opensearch-dashboards/*.

**Comment by dblock** [comment]
I opened a feature request #365 to support rolling upgrades in the future.

**Comment by kavilla** [comment]
As linked in the PRs we have decided to restore keys (_magic_ words) related to functionality. So we restored the default index to .kibana and others. Currently working on timelion. This is to help data stored be seamlessly upgrade from 7.10 Kibana to OpenSearch Dashboards 1.0. This should have no change in the visual/branding but internally keep the code the same.

**Comment by tmarkley** [comment]
### Investigation for URLs containing “kibana”:

It doesn’t look like we need to worry about any shared link objects that contain “kibana”/“opensearch-dashboards”. The only two pages I found with the tiny URL generation is `/app/discover` and `/app/dashboards`. 

However, I think we would need to consider the defaultRoute saved object. It’s possible to have something like `/app/management/kibana`.

There are the URLs that I found that we would need to redirect to from their “kibana” counterpart:
* `/app/management/opensearch-dashboards` ➡️ `/app/management/kibana` :white_check_mark: (still routes to the correct page)
* `/app/management/opensearch-dashboards/indexPatterns` ➡️ `/app/management/kibana/indexPatterns` :white_check_mark: (still routes to the correct page)
* `/app/management/opensearch-dashboards/objects` ➡️ `/app/management/kibana/objects` :x: (routes to the Stack Management page)
* `/app/management/opensearch-dashboards/settings` ➡️ `/app/management/kibana/settings` :x: (routes to the Stack Management page)
* `/app/opensearch_dashboards_overview#/` ➡️ *Is there an equivalent “kibana” URL for this page?* :question:

Should we have redirects for these specific pages or something more generic? I’m not sure where the best spot for that logic is.

**Comment by kavilla** [comment]
> ### Investigation for URLs containing “kibana”:
> 
> It doesn’t look like we need to worry about any shared link objects that contain “kibana”/“opensearch-dashboards”. The only two pages I found with the tiny URL generation is `/app/discover` and `/app/dashboards`.
> 
> However, I think we would need to consider the defaultRoute saved object. It’s possible to have something like `/app/management/kibana`.
> 
> There are the URLs that I found that we would need to redirect to from their “kibana” counterpart:
> 
>     * `/app/management/opensearch-dashboards` ➡️ `/app/management/kibana` ✅ (still routes to the correct page)
> 
>     * `/app/management/opensearch-dashboards/indexPatterns` ➡️ `/app/management/kibana/indexPatterns` ✅ (still routes to the correct page)
> 
>     * `/app/management/opensearch-dashboards/objects` ➡️ `/app/management/kibana/objects` ❌ (routes to the Stack Management page)
> 
>     * `/app/management/opensearch-dashboards/settings` ➡️ `/app/management/kibana/settings` ❌ (routes to the Stack Management page)
> 
>     * `/app/opensearch_dashboards_overview#/` ➡️ _Is there an equivalent “kibana” URL for this page?_ ❓
> 
> 
> Should we have redirects for these specific pages or something more generic? I’m not sure where the best spot for that logic is.

appending timelion. right not that is restored in the https://github.com/opensearch-project/OpenSearch-Dashboards/pull/390 since it has to be for the application to be backwards compatible but if we migrate that to be fully timeline then the url will change.

**Comment by kavilla** [comment]
All DQL stuff is untouched on how the data is stored should be backwards compatible with no restoration.

**Comment by kavilla** [comment]
For backwards compatibility testing, what we have been doing is using the `.kibana` index created and updated by a 7.10.3 artifact of Kibana. Then having sample data loaded, non-default settings, added visualizations, and queries added by utilizing the application. So when testing if our changes are backwards compatible, we update OpenSearch Dashboards to point to the cluster with the indices created by the 7.10.3 artifact and run the application. Ensuring it builds correctly, runs correctly, loads sample data data, settings, visualizations, and queries. I also run some basic queries and filtering on the dashboards to match the data. For example, one smoke test is using the kibana sample flight data and checking if the number of flights cancelled is ~40 flights. Then testing if the Timeline sample data for web logs in the pass 8 weeks shows peaks and valleys. Also checking when we modify the data or settings it saves as expected by checking the indices and exporting the objects.

After the smoke testing is satisfied, we just run unit, integ tests, and functional tests to ensure the application works as expected. The functional tests has sample data loaded that matches is structured in a way that fails to load if the application isn't backwards compatible .

There could potentially be more work to be done about automation related to backwards compatible.

**Comment by kavilla** [comment]
Will re-open to verify telemetry doesn't block people.

**Comment by kavilla** [comment]
Some test workflow how I was able to verify BWC.

Install ODFE
* Navigate to https://opendistro.github.io/for-elasticsearch/downloads.html#try 
* Download docker-compose.yml
* Run `docker-compose up`

Add data
* Navigate to localhost:5601 and login into global with admin/admin
* Navigate to home#/tutorial_directory/sampleData
* Add all sample data

Add Timelion visualization
* Navigate to Visualize > Create visualization > Timelion 
* Save with name and description

Add filter and query
* Navigate to Dashboard > [Logs] Web Traffic
* Add filter > Field: `machine.os` Operator: `is` Value: `osx` Custom label: `osx filter`
* Add query > `resp=200` > Save query with name and description and `Include Filters`

Update default page
* Navigate to overview
* Click `Make this my landing page`

Add Settings
* Navigate to Stack Management > Advanced Settings
* Set Dark Mode
* Set Timelion:default_columns: `4`
* Set Timelion:max_buckets: `2004`

Disable Shard Allocation
```
PUT _cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.enable": "primaries"
  }
}
```

Stop indexing and perform a flush: perform a flush to speed up shard recovery.
```
POST /_flush
```

Copy data
* In the same location of your `docker-compose.yml` create `data/data1` and `data/data2`
* To see what is in the docker container run `docker exec -it $CONTAINER_NAME /bin/bash`
* Run `docker cp odfe-node1:/usr/share/elasticsearch/data/. ./data/data1`
* Run `docker cp odfe-node2:/usr/share/elasticsearch/data/. ./data/data2` 

Shut down nodes and kibana
* Run `docker-compose down`

Install OpenSearch
* Make a folder and go into `opensearch`
* Create a file called `docker-compose.yml` and copy the following contents:
```
version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      #- ./custom-opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      #- ./custom-opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    networks:
      - opensearch-net
  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_URL: https://opensearch-node1:9200
      OPENSEARCH_HOSTS: https://opensearch-node1:9200
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:
```


Run OpenSearch and copy data into OpenSearch
* In your OpenSearch folder run `docker-compose up`
* In a different window:
  * Run `docker cp ./data/data1 opensearch-node1:/usr/share/opensearch/data/`
  * Run `docker cp ./data/data2 opensearch-node2:/usr/share/opensearch/data/`
  * Give permissions to the data folders:
    * `docker exec -it $CONTAINER_NAME /bin/bash`
    * `chown -R 1000:1000 data`
* Stop the clusters and the re-run `docker-compose up`

Verify dashboards, data, queries, filters, visualizations are all there.
