### ISSUE TITLE
Creating index-pattern via API with ansible [BUG]

### ISSUE THREAD

**Issue by Zujiry** [opensearch-project/OpenSearch-Dashboards#4030]
**Describe the bug**

I want to create index-patterns via REST-API but get the error:
````
"Bad Request", "message": "[request body.attributes]: expected value of type [object] but got [undefined]" 400
````

**To Reproduce**
1. Setup an ansible playbook with the following task:
````
- name: Create index pattern
      ansible.builtin.uri:
          url: "http://localhost:5601/api/saved_objects/index-pattern/{{ opensearch_index.name }}"
          method: POST
          user: "{{ opensearch_admin_user }}"
          password: "{{ opensearch_admin_pass }}"
          force_basic_auth: yes
          validate_certs: no
          body_format: json
          body: "{{ lookup('ansible.builtin.template', 'templates/ism_index_pattern.json.j2') }}"
          headers:
            Content-Type: "application/json"
            osd-xsrf: true
            securitytenant: "{{ opensearch_index.name }}-tenant"
      register: _result
      until: _result.status == 200
      retries: 5
      delay: 1
````

opensearch_index.name being e.g. "example-index". The tenant is already created via securityconfig.

With the JSON file:

templates/ism_index_pattern.json.j2
````
{
  "index_pattern": {
    "title": "{{ opensearch_index.name }}*",
    "timeFieldName": "@timestamp"
  }
}
````
2. Get the Error:
````
"Bad Request", "message": "[request body.attributes]: expected value of type [object] but got [undefined]" 400
````

**Expected behavior**

The index-pattern should be created. 

**OpenSearch Version**
1.3.9

**Dashboards Version**
1.3.9

**Plugins**

opensearch-alerting                  1.3.9.0
opensearch-anomaly-detection         1.3.9.0
opensearch-asynchronous-search       1.3.9.0
opensearch-cross-cluster-replication 1.3.9.0
opensearch-index-management          1.3.9.0
opensearch-job-scheduler             1.3.9.0
opensearch-knn                       1.3.9.0
opensearch-ml                        1.3.9.0
opensearch-observability             1.3.9.0
opensearch-performance-analyzer      1.3.9.0
opensearch-reports-scheduler         1.3.9.0
opensearch-security                  1.3.9.0
opensearch-sql                       1.3.9.0
