### ISSUE TITLE
[BUG][dashboard dataSource] enabled data_source, got "Definition of plugin "dataSource" not found and may have failed to load."

### ISSUE THREAD

**Issue by Stainless5792** [opensearch-project/OpenSearch-Dashboards#4054]
**Describe the bug**

In version 2.7.0, once enabled the data_source, got the exception on the page with below error :
```
Version: 2.7.0
Build: 6100
Error: Definition of plugin "dataSource" not found and may have failed to load.
read@https://my-opensearch/6100/bundles/core/core.entry.js:15:640644
_callee3$@https://my-opensearch/6100/bundles/core/core.entry.js:15:645356
u@https://my-opensearch/6100/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:382:1685537
c/o._invoke</<@https://my-opensearch/6100/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:382:1685291
M/</<@https://my-opensearch/6100/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:382:1685900
plugin_asyncGeneratorStep@https://my-opensearch/6100/bundles/core/core.entry.js:15:641099
_next@https://my-opensearch/6100/bundles/core/core.entry.js:15:641441
plugin_asyncToGenerator/</<@https://my-opensearch/6100/bundles/core/core.entry.js:15:641585
plugin_asyncToGenerator/<@https://my-opensearch/6100/bundles/core/core.entry.js:15:641328
createPluginInstance@https://my-opensearch/6100/bundles/core/core.entry.js:15:645922
_callee$@https://my-opensearch/6100/bundles/core/core.entry.js:15:643727
u@https://my-opensearch/6100/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:382:1685537
c/o._invoke</<@https://my-opensearch/6100/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:382:1685291
M/</<@https://my-opensearch/6100/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:382:1685900
plugin_asyncGeneratorStep@https://my-opensearch/6100/bundles/core/core.entry.js:15:641099
_next@https://my-opensearch/6100/bundles/core/core.entry.js:15:641441
plugin_asyncToGenerator/</<@https://my-opensearch/6100/bundles/core/core.entry.js:15:641585
plugin_asyncToGenerator/<@https://my-opensearch/6100/bundles/core/core.entry.js:15:641328
setup@https://my-opensearch/6100/bundles/core/core.entry.js:15:644003
_callee$@https://my-opensearch/6100/bundles/core/core.entry.js:15:654848
u@https://my-opensearch/6100/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:382:1685537
c/o._invoke</<@https://my-opensearch/6100/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:382:1685291
M/</<@https://my-opensearch/6100/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:382:1685900
plugins_service_asyncGeneratorStep@https://my-opensearch/6100/bundles/core/core.entry.js:15:648845
_next@https://my-opensearch/6100/bundles/core/core.entry.js:15:649205
```

<img width="1021" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/5257915/e2dea300-21e0-47e6-aba8-cabfd09fd67d">

**To Reproduce**
1. use the operator to install the opensearch cluster,
2. enable the data_source 
3. got the error 

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-cluster
  namespace: opensearch
spec:
  general:
    serviceName: my-cluster
    version: 2.7.0
  dashboards:
    enable: true
    version: 2.7.0
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
    additionalConfig:
      ## got error once enabled !!
      data_source.enabled: "true"
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "50Gi"
      nodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"
```

**Expected behavior**
The page should work as normal.

**OpenSearch Version**
2.7.0

**Dashboards Version**
2.7.0

**Plugins**

Please list all plugins currently enabled.
data_source

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: k8s
