### ISSUE TITLE
[Research] OUI usage audit in the `tile_map` plugin

### ISSUE THREAD

**Issue by BSFishy** [opensearch-project/OpenSearch-Dashboards#4109]
## Audit

Looking in the `tile_map` plugin, there are only 2 Sass files. They are [`src/plugins/tile_map/public/_tile_map.scss`](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/tile_map/public/_tile_map.scss) and [`src/plugins/tile_map/public/index.scss`](https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/tile_map/public/index.scss). `index.scss` just imports `_tile_map.scss`.

`_tile_map.scss` defines 2 classes:

```scss
// SASSTODO: Does this selector exist today?
.tilemap {
  margin-bottom: 6px;
  border: $euiBorderThin;
  position: relative;
}

/**
* 1. Visualizations have some padding by default but tilemaps look nice flush against the edge to maximize viewing
* space.
*/
// SASSTODO: Does this selector exist today?
.tile_map {
  padding: 0; /* 1. */
}
```

Neither of these classes are actually used anywhere. Commenting them out doesn't change the visual appearance of the visualization at all. Additionally, the `className` prop isn't used anywhere in the `tile_map` plugin.

## Conclusion

Both of the Sass files can be removed safely.
