### ISSUE TITLE
Hide/Show authentication method in multi data source plugin based on configuration

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/OpenSearch-Dashboards#5694]
**Is your feature request related to a problem? Please describe.**

Yes, I wanted to customize authentication methods in multi data source plugin. Sometime I don't need particular auth method to be supported in multi data source plugin because of security or any other concern. I should have flexibility to show only authentication method which I wanted.

Also if there is only one option for selection, make dropdown or selection option read only.

**Describe the solution you'd like**

Add configuration in yml file and hide/show the auth options based on configuration.

**Comment by zengyan-amazon** [comment]
in addition to hide/show authentication methods, we only support basic auth(username/password) and static IAM credentials authentication methods. We may consider to make it easier for developers to add other auth methods via plugin, e.g. supporting API key etc.

**Comment by bandinib-amzn** [comment]
Right now we are supporting No Authentication, Basic Authentication(username/password) and AWS SigV4  (static IAM credentials) authentication methods. Although we propose to add interface in multi data source plugin to register authentication method by plugin in #5692, it would be too many plugins if we decide to move each authentication method in plugins. That's why I feel we should keep existing auth methods as part of core code and provide config options to manage them (hid/show).

I'll mark this issue as follow up item in #5692

**Comment by bandinib-amzn** [comment]
1) To achieve requested feature, we can add configuration as below:
```
# Set enabled false to hide authentication method in OpenSearch Dashboards.
# If this setting is commented then all 3 options will be available in OpenSearch Dashboards.
# Default value will be considered to True.
data_source.authTypes:
  NoAuthentication:
    enabled: true
  UsernamePassword:
    enabled: true
  AWSSigV4:
    enabled: true
```
Please feel free to optimize/modify as per your preference

2) During [data_source_management plugin setup](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/data_source_management/public/plugin.ts#L44), read config values and register authentication methods in auth registry. 

3) Refactor below code, to read authentication option from registry.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/e08bf3059896449d2c008059c47b0b3de8da8c9e/src/plugins/data_source_management/public/components/create_data_source_wizard/components/create_form/create_data_source_form.tsx#L600-L606

4) Add `readOnly` prop to above `super select` component. readOnly value should be true if there is only one option in auth registry.
