### ISSUE TITLE
[BUG] Opensearch dashobard user name/password login fails when clientauth_mode is set to "REQUIRE"

### ISSUE THREAD

**Issue by nitinjagjivan** [opensearch-project/OpenSearch-Dashboards#5705]
**Describe the bug**

For security, I want to make enable client certificate authentication mandatory on the OpenSearch nodes.
Following [Client certificate authentication - OpenSearch documentation 3](https://opensearch.org/docs/latest/security-plugin/configuration/client-auth/)
I set:

plugins.security.ssl.http.clientauth_mode: "REQUIRE"

The OpenSearch nodes are able to communicate, and I can make API calls using client certs and the admin username/password.
The Dashboard can’t connect.
Has anyone got this working?

**To Reproduce**
Deploy opensearch and opensearch-dashboards with below settings:
```
cat config/opensearch.yml
cluster.name: my-cluster
network.host: 0.0.0.0

plugins:
  security:
    ssl:
      transport:
        pemcert_filepath: certs/opensearch-transport.crt.pem
        pemkey_filepath: certs/opensearch-transport.key
        pemtrustedcas_filepath: certs/chain-ca.pem
        enforce_hostname_verification: false
        pemkey_password: mypassword
      http:
        enabled: true
        enable_openssl_if_available: true
        pemcert_filepath: certs/opensearch-http.crt.pem
        pemkey_filepath: certs/opensearch-http.key
        pemtrustedcas_filepath: certs/chain-ca.pem
        pemkey_password: mypassword
        clientauth_mode: REQUIRE
    allow_unsafe_democertificates: false
    allow_default_init_securityindex: true
    authcz:
      admin_dn:
        - "CN=opensearch-admin, OU=CES, O=HCL, C=US"
    audit.type: internal_opensearch
    enable_snapshot_restore_privilege: true
    check_snapshot_restore_write_privileges: true
    restapi:
      roles_enabled: ["all_access", "security_rest_api_access"]
    system_indices:
      enabled: true
      indices:
        [
          ".opendistro-alerting-config",
          ".opendistro-alerting-alert*",
          ".opendistro-anomaly-results*",
          ".opendistro-anomaly-detector*",
          ".opendistro-anomaly-checkpoints",
          ".opendistro-anomaly-detection-state",
          ".opendistro-reports-*",
          ".opendistro-notifications-*",
          ".opendistro-notebooks",
          ".opendistro-asynchronous-search-response*",
        ]
```

opensearch-dashboard.yml
```
logging:
    verbose: false
server:
    name: dashboards
    host: 0.0.0.0
    basePath: "/dashboards"
    ssl:
        enabled: true
        key: certs/elasticstack.key.pem
        certificate: certs/elasticstack.cert.pem
opensearch:
    hosts: https://opensearch-master-node:9200
    requestTimeout: 300000
    username: adminq
    password: mypassword
    ssl:
        certificateAuthorities: certs/chain-ca.pem
        certificate: certs/opensearch-admin.crt.pem
        key: certs/opensearch-admin.key
        verificationMode: none
        alwaysPresentCertificate: true
        keyPassphrase: mypassword
```

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**
