### ISSUE TITLE
Suggestion to update thresholds for first-time-contributor,repeat-contributor

### ISSUE THREAD

**Issue by seraphjiang** [opensearch-project/OpenSearch-Dashboards#6242]
**Is your feature request related to a problem? Please describe.**

the question related to thresholds of first-time-contributor,repeat-contributor

### current setup
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/0dce00a806bf8815ca84802541010767b6b3a8bd/.github/workflows/github-workflow-badger.yml#L19

```
          badges: '[first-time-contributor,repeat-contributor,valued-contributor,seasoned-contributor,all-star-contributor,distinguished-contributor]'
          thresholds: '[0,3,6,13,25,50]'
```

### recommended setup
to be accurate, should we change thresholds of repeat-contributor to 1? currently people contributed 1~2 labeled as first-time contributor

some references

https://github.com/cdklabs/github-merit-badger

```
steps:
  - uses: aws-github-ops/github-merit-badger@main
    id: github-merit-badger
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      badges: '[first-time-contributor,repeat-contributor,allstar-contributor]'
      thresholds: '[0,1,5]'
      days: 365
```

```
steps: 
  - uses: aws-github-ops/github-merit-badger@main
    id: github-merit-badger
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      badges: '[first-time-contributor,repeat-contributor,allstar-contributor]'
      thresholds: '[0,1,5]'
      title-prefixes: '[feat,fix]'
```
