### ISSUE TITLE
[BUG] Docker Image's `I18N_LOCALE` environment variable does not seem to work

### ISSUE THREAD

**Issue by linghengqian** [opensearch-project/OpenSearch-Dashboards#8075]
**Describe the bug**

- Docker Image's `I18N_LOCALE` environment variable does not seem to work. But `I18N_LOCALE` is actually documented as follows. See https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.16.0/src/dev/build/tasks/os_packages/docker_generator/resources/bin/opensearch-dashboards-docker#L54 .
- PRs like #7686 show that i18n is actually ready, if I understand correctly? But I can't find any description of i18n in the configuration section of the documentation.

**To Reproduce**

1. Create the following `docker-compose.yml` file.
```yaml
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.16.0
    expose:
      - 9200
      - 9600
    environment:
      discovery.type: single-node
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: opensearchNode1Test
    restart: always
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.16.0
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
      I18N_LOCALE: "zh-CN"
    restart: always
    ports:
      - "5601:5601"
volumes:
  opensearch-data1:
```

2. Visit `localhost:5601` and log in using the `admin` and `opensearchNode1Test` user passwords.
- ![image](https://github.com/user-attachments/assets/0dc2cd7b-2a4d-45df-b8dd-92d980eff852)

3. At this time, the Web UI is still in English, not the Chinese `zh-CN` set by `I18N_LOCALE`.
- ![image](https://github.com/user-attachments/assets/2c27256b-bc90-4c1d-aafd-b21ab03ea886)

**Expected behavior**
- The `I18N_LOCALE` environment variable of the Docker Image works.

**OpenSearch Version**
Please list the version of OpenSearch being used.
- `2.16.0`

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.
- `2.16.0`

**Plugins**
Please list all plugins currently enabled.

- Only built-ins.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: [e.g. iOS] `Ubuntu 22.04.4 WSL`
 - Browser and version [e.g. 22]  `Microsoft Edge 128.0.2739.63`

**Additional context**

- Null.

**Comment by linghengqian** [comment]
> 遇到同样问题，检测了对多遍以为配置没生效，结果容器中配置已生效只是没有应用到语言包

- @ananzh I saw #7686 introduced the ability to dynamically change the i18n language via URL. But is there a corresponding documentation PR? And what else needs to be done on the dashboards side to make the i18n configuration permanent?

**Comment by linghengqian** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8414#discussion_r1786514899 has a pretty good explanation, and the 2 different opensearch dashboard plugins will be merged in the future. But where is the original discussion?

> We have https://github.com/opensearch-project/dashboards-i18n/blob/main/DEVELOPER_GUIDE.md and https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/packages/osd-i18n. Some day, I will merge those into one and add my future vision into it.

**Comment by fanzhengweiwudi** [comment]
> 遇到同样问题，检测了对多遍以为配置没生效，结果容器中配置已生效只是没有应用到语言包

你解决了吗?怎么解决的?

**Comment by linghengqian** [comment]
I identified the root cause: although the Docker image `opensearchproject/opensearch-dashboards:3.8.0` contains https://github.com/opensearch-project/OpenSearch-Dashboards/blob/3.8.0/src/translations/zh-CN.json (as found in the official source code), it is missing the https://github.com/opensearch-project/OpenSearch-Dashboards/blob/3.8.0/src/.i18nrc.json registration manifest. Consequently, Dashboards returns the `zh-CN` formatting settings but fails to load any message strings.

**Comment by linghengqian** [comment]
- Regarding `compose.yaml`,
```yaml
name: opensearch-apm
services:
  opensearch:
    image: opensearchproject/opensearch:3.8.0
    restart: unless-stopped
    environment:
      discovery.type: single-node
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "Developer@123"
    ports:
      - "19200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.8.0
    restart: unless-stopped
    environment:
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      I18N_LOCALE: "zh-CN"
    volumes:
      - ./dashboards-i18nrc.json:/usr/share/opensearch-dashboards/src/.i18nrc.json:ro
    ports:
      - "15601:5601"
    depends_on:
      - opensearch
  data-prepper:
    image: opensearchproject/data-prepper:2.16.0
    restart: unless-stopped
    volumes:
      - ./pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml:ro
    ports:
      - "21890:21890"
      - "21891:21891"
      - "21892:21892"
    depends_on:
      - opensearch
volumes:
  opensearch_data:
```
- For `dashboards-i18nrc.json`,
```json
{
  "translations": [
    "translations/zh-CN.json"
  ]
}
```
- For `pipelines.yaml`,
```yaml
otel-logs-pipeline:
  source:
    otel_logs_source:
      ssl: false
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index: otel_logs
otel-metrics-pipeline:
  source:
    otel_metrics_source:
      ssl: false
  processor:
    - otel_metrics:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index: otel_metrics
otel-trace-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  sink:
    - pipeline:
        name: raw-trace-pipeline
    - pipeline:
        name: service-map-pipeline
raw-trace-pipeline:
  source:
    pipeline:
      name: otel-trace-pipeline
  processor:
    - otel_traces:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index_type: trace-analytics-raw
service-map-pipeline:
  source:
    pipeline:
      name: otel-trace-pipeline
  processor:
    - service_map:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        index_type: trace-analytics-service-map
```
- Then,
```bash
docker compose up -d
```
