### ISSUE TITLE
[BUG] Missing doc regarding opensearch_security.cookie/session

### ISSUE THREAD

**Issue by SebastianThorn** [opensearch-project/OpenSearch-Dashboards#8266]
**Describe the bug**

Documentation regarding the following parameters is missing

```yaml
opensearch_security.cookie.ttl: 3600000
opensearch_security.session.keepalive: true
opensearch_security.session.ttl: 3600000
```
They are refereed to in this forum-post: https://forum.opensearch.org/t/cookie-session-timeout/8508

`opensearch_security.cookie.secure` is documented in here: https://opensearch.org/docs/latest/install-and-configure/install-dashboards/tls/

**Expected behavior**
Documentation on all parameters

**Dashboards Version**
2.17

**Additional context**
I enjoy the was Grafana has it with all parameters on a single page, yes it's long, but it is all there.
https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
