### ISSUE TITLE
Migrating Dashboards from Kibana to OpensearchDashboard

### ISSUE THREAD

**Issue by riteshsonawane1372** [opensearch-project/OpenSearch-Dashboards#9740]
**Describe the bug**

I want to migrate all my dashboards from Kibana `8.15.4` to OpensearchDashboard `2.19.1`

I exported the dashboard from Kibana `8.15.4` to Opensearch `2.19.1`. Dashboards were imported with no error. But whenever I try to open a dashboard I get this error for all dashboards. 
```
Could not find reference "panel_37fd5af0-2349-42a9-9fd8-f18ce7c0dc42"
```

Apart from this all indices are imported, and I can see the data.

**To Reproduce**
1. Install kibana `8.15.4` and create a dashboard 
2. Export these dashboard and try to import it to Opensearch dashboard `2.19.1` (same issue when I tried importing these dashboards from kibana 8.15.4 to kibana 7.10.2)

**Expected behavior**

**OpenSearch Version**
2.19.1

**Dashboards Version**
2.19.1

**Plugins**

opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-custom-codecs
opensearch-flow-framework
opensearch-geospatial
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ltr
opensearch-ml
opensearch-neural-search
opensearch-notifications
opensearch-notifications-core
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-security-analytics
opensearch-skills
opensearch-sql
opensearch-system-templates
query-insights
repository-s3

**Screenshots**

**Host/Environment (please complete the following information):**
 - Kubernetes Operator installation with 2.19.1 version. Below is the config 
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
  namespace: dev
spec:
  security:
    tls:
      transport:  
        generate: true  
      http:  
        generate: true  
    config:
      securityConfigSecret:
        name: "opensearch-securityconfig"
      adminCredentialsSecret:
        name: "opensearch-cred"
  general:
    serviceName: opensearch-cluster
    version: 2.19.1
    pluginsList: ["repository-s3"]
    additionalConfig:
      reindex.ssl.verification_mode: none
    keystore: 
      - secret:
          name: opensearch-cred
        keyMappings:
          access_key: s3.client.default.access_key
          secret_key: s3.client.default.secret_key
    snapshotRepositories: 
      - name: ""
        type: s3
        settings:
          bucket:  
          region: us-east-1
          base_path: dev
    setVMMaxMapCount: true
  dashboards:
    opensearchCredentialsSecret:
      name: opensearch-cred
    enable: true
    tls:
      enable: false 
      generate: false
    version: 2.19.1
    replicas: 1
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "30Gi"
      persistence:
        pvc:
          storageClass: gp3-encrypted
          accessModes:
          - ReadWriteOnce
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"
        - "cluster_manager"
        - "master"
```

**Additional context**
