### ISSUE TITLE
[BUG] role not working as expected in OpenSearch Dashboards

### ISSUE THREAD

**Issue by atalakey4work** [opensearch-project/OpenSearch-Dashboards#9858]
**Describe the bug**

OpenSearch Dashboards queries all indices that match the selected index pattern. If the user doesn’t have access to all of them, it fails. I am trying to setup role and role binding in such a way that users have access to documents from specific Indices without using DLS.

I have the following setup in an OpenSearch cluster:

- Indices:
    - k8s-production-2025
    - k8s-preprod-2025

- index pattern:
    - k8s-*

- role:

```
    k8s-production:
      reserved: true
      hidden: false
      cluster_permissions:
        - cluster_composite_ops_ro
      index_permissions:
      - index_patterns:
        - "k8s-production-*"
        allowed_actions:
        - read
      tenant_permissions:
      - tenant_patterns:
        - k8s-production
        allowed_actions:
        - "kibana_all_read"
```

- role mapping:

```
    k8s-production:
      reserved: true
      hidden: false
      users:
      - test-user
```

Querying via OpenSearch API works as expected. On the other hand, in OpenSearch Dashboards, when I visit the "Discover" page using the "test-user" and select the "k8s-*" index pattern no logs are displayed and I get the following error:

```
Error
    at fetch_Fetch.fetchResponse (https://logs.tamkeen.cloud/8430/bundles/core/core.entry.js:15:412479)
    at async interceptResponse (https://logs.tamkeen.cloud/8430/bundles/core/core.entry.js:15:407289)
    at async https://logs.tamkeen.cloud/8430/bundles/core/core.entry.js:15:410181
```

When I update the role's index_patterns values to "k8s-*" everything works but I see documents from both indices.

When OpenSearch Dashboards runs a query using the k8s-* pattern, it attempts to query all indices matching that pattern — i.e., both k8s-production-2025 and k8s-preprod-2025. If the logged-in user (test-user) has permissions only on k8s-production-*, then querying k8s-* results in a 403 or partial failure, because access to k8s-preprod-2025 is denied.

**Expected behavior**
Search in Dashboards should return the same result as API does.

**OpenSearch Version**
3.0.0

**Dashboards Version**
3.0.0

**Plugins**

```
opensearch-alerting                  3.0.0.0
opensearch-anomaly-detection         3.0.0.0
opensearch-asynchronous-search       3.0.0.0
opensearch-cross-cluster-replication 3.0.0.0
opensearch-custom-codecs             3.0.0.0
opensearch-flow-framework            3.0.0.0
opensearch-geospatial                3.0.0.0
opensearch-index-management          3.0.0.0
opensearch-job-scheduler             3.0.0.0
opensearch-knn                       3.0.0.0
opensearch-ltr                       3.0.0.0
opensearch-ml                        3.0.0.0
opensearch-neural-search             3.0.0.0
opensearch-notifications             3.0.0.0
opensearch-notifications-core        3.0.0.0
opensearch-observability             3.0.0.0
opensearch-performance-analyzer      3.0.0.0
opensearch-reports-scheduler         3.0.0.0
opensearch-security                  3.0.0.0
opensearch-security-analytics        3.0.0.0
opensearch-skills                    3.0.0.0
opensearch-sql                       3.0.0.0
opensearch-system-templates          3.0.0.0
query-insights                       3.0.0.0
```

**Host/Environment (please complete the following information):**
 - OS: Kubernetes
 - Browser and version: Chrome
