### ISSUE TITLE
[Meta] Docker-compose configs for Prometheus data-source integration

### ISSUE THREAD

**Issue by lukas-vlcek** [opensearch-project/OpenSearch-Dashboards#9915]
This is a META ticket.

This ticket define two common `docker-compose` configurations that consists of:
- Single **OpenSearch** node
- Single **OpenSearch Dashboards** node
- Single **Prometheus** service

The first configuration does not use any security, the second configuration uses the demo OpenSearch security. They are used in follow up tickets:
- #9916 
- #9917
- #9918 

These configurations use OpenSearch version `2.17.1` but in some follow-up tickets different versions of OpenSearch can be used as well (`2.19.2` or `3.0.0` - _pay attention to this please_).

Prometheus is always the latest version.

## Without Security

File: `docker-compose-no-security.yml`

```yml
services:
  opensearch-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.type=single-node
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "plugins.query.datasources.encryption.masterkey=5e3dc78f06ef582dedbb5154"
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.17.1 # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      - data_source.enabled=true
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-net
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    expose:
      - "9090"
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:
```

## With Security

File: `docker-compose.yml`

```yml
services:
  opensearch-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.type=single-node
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD} 
      - "plugins.query.datasources.encryption.masterkey=5e3dc78f06ef582dedbb5154"
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.17.1 # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      - data_source.enabled=true
      - 'OPENSEARCH_HOSTS=["https://opensearch-node1:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - opensearch-net
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    expose:
      - "9090"
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net:
```

## Additional files

Besides `docker-compose` configuration files assume there is also `.env` file with the following content:

```
OPENSEARCH_INITIAL_ADMIN_PASSWORD=Sup13#!P1##w0rd
```

## Related tickets

- Is this ticket related? https://github.com/opensearch-project/OpenSearch-Dashboards/issues/9221
