### ISSUE TITLE
[BUG] Enabling data-sources results in Observability Logs missing

### ISSUE THREAD

**Issue by vinylen** [opensearch-project/OpenSearch-Dashboards#9926]
**Describe the bug**

When we enable data-source for OpenSearch-Dashboards, we lose the ability to access Observability -> Logs. The option to view Observability Logs is missing from the UI.
```
data_source.enabled: "true"
data_source.ssl.verificationMode: none
```
When we disable data-sources and restart Dashboards, we regain the ability to view Observability Logs.

**To Reproduce**
1. Run this docker-compose file:
```
services:
  opensearch-node1: 
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster 
      - node.name=opensearch-node1 
      - discovery.seed_hosts=opensearch-node1,opensearch-node2 
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2 
      - bootstrap.memory_lock=true 
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=hardadminpassword123! 
    ulimits:
      memlock:
        soft: -1 
        hard: -1
      nofile:
        soft: 65536 
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data 
    ports:
      - 9200:9200 
      - 9600:9600 
    networks:
      - opensearch-net 
  opensearch-node2:
    image: opensearchproject/opensearch:3.0.0 
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=hardadminpassword123!
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0 
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 
    expose:
      - "5601" 
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]' 
      DATA_SOURCE_ENABLED: "true"
      DATA_SOURCE_SSL_VERIFICATIONMODE: "none"
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:

networks:
  opensearch-net:


```
2. Access Dashboards via http://127.0.0.1:5601 and go to Observability. The option to view Logs is not showing up.
3. Remove these lines from the `environment` section for opensearch-dashboards:
```
DATA_SOURCE_ENABLED: "true"
DATA_SOURCE_SSL_VERIFICATIONMODE: "none"

```
4. Run `docker compose down && docker compose up -d`
5. Access Dashboards via http://127.0.0.1:5601 and go to Observability. The option to view Logs is now showing up as expected.

**Expected behavior**
Enabling data-source support for opensearch-dashboards should not result in Observability -> Logs being affected and missing.

**OpenSearch Version**
I've tested this on 2.19.1 and 3.0.0

**Dashboards Version**
I've tested this on 2.19.1 and 3.0.0

**Plugins**
No plugin out of the ones that are shipped by default have been enabled.

**Screenshots**

![Image](https://github.com/user-attachments/assets/3d238ac2-0bde-41f5-8b61-8104932f3bc7)

**Host/Environment (please complete the following information):**
 - Mozilla Firefox
 - Google Chrome

**Additional context**

I've also created a forum thread for it [here](https://forum.opensearch.org/t/observability-logs-missing-from-dashboards-in-3-0/24752?u=victor).
